language: java
sudo: false
script: gradle build
before_install:
  gradle -b wrapper.gradle wrapper
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main