version: "3"
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=javadeveloper
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:33060
    networks:
      - mynet
  app:
    build:
      dockerfile: ./app/Dockerfile
      context: .
    container_name: myapp
    ports:
    - 80:8080
    networks:
      - mynet
    depends_on:
      - db

networks:
  mynet: